### ISSUE TITLE
Fix 'bdSeq' number language and ensure it is a byte

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#10]

**Comment by jbrzozoski** [comment]
Not critical, but a thought:

Sometimes on systems which have a RTC but no non-volatile memory, I have used the timestamp of when I created the NDEATH LWT message as my bdSeq for that connection.  It's guaranteed to be unique for that device forever, and always increasing.  If you switch to a uint8 that is no longer feasible.

**Comment by wes-johnson** [comment]
Good point. I had this up for review at our meeting tomorrow. I'm inclined to leave it all as is for the initial release of the spec and will propose that tomorrow.

**Comment by wes-johnson** [comment]
This is going to be left as is for the initial release of the spec. The BD sequence numbers will still be 0-255 and the sequence BD number will still use a uint64. This will allow us to expand the range of sequence numbers in the future if we decide to.
