### ISSUE TITLE
UInt32 datatype in long_value or int_value?

### ISSUE THREAD

**Issue by jbrzozoski** [eclipse/sparkplug#102]
How to properly transport a UInt32 datatype disagrees between the spec and the reference implementation.  Chapter 6, section 6.4.17 contains:

```
** _UInt32_
*** Unsigned 32-bit integer
*** Google Protocol Buffer Type: uint32
*** Sparkplug enum value: 7
```

That says that a UInt32 datatype value should go in a protobuf type of uint32, yet the reference implementation and Ignition both use the "uint64 long_value" field.

**Comment by wes-johnson** [comment]
This is fixed per: https://github.com/eclipse/tahu/pull/202.
