### ISSUE TITLE
Invalid data shown on pirmary application if EoN starts before primary application

### ISSUE THREAD

**Issue by pietercardoen** [eclipse/sparkplug#135]
The sparkplug specification version 2.2 specifies: "If EoN nodes are already connected to the MQTT Server infrastructure, the Primary Application will synchronize with them.".

In this scenario:
* Edge node starts in advance of the primary application
* Edge node sends birth message
* Edge node sends one or multiple NDATA messages
* Primary application starts
* Primary application processes NBIRTH message

At this point, the primary application will show all metrics of the EdgeNode but data can show erroneous values as some NDATA messages have been transmitted after the NBIRTH message and before the primary application startup. If the edge node is only transmitting data on change, it could be that this error persists for a long time.

How can this be avoided?

**Comment by I-Campbell** [comment]
Please see the clarification here:
https://github.com/eclipse/sparkplug/blob/develop/specification/src/main/asciidoc/chapters/Sparkplug_5_Operational_Behavior.adoc

Basically, the Primary Application will not know about the NBIRTH until the edge sends a fresh NBIRTH.
The Edge should send a fresh NBIRTH as a result of receiving a STATE/<PrimaryhostID> := ONLINE
If not, the PrimaryHost will anyway reject any xDATA or DBIRTH messages.  Usually it will send a NCMD with metric 'Node Control/Rebirth', which should also trigger an NBIRTH.

So in no scenario will erroneous values (old values which are NOT marked as stale) be shown.

Please close the ticket if this answers it for you
