### ISSUE TITLE
NBIRTH QoS and retained

### ISSUE THREAD

**Issue by pietercardoen** [eclipse/sparkplug#136]
AFAIK, I haven't found specification of QoS and retain flag for node birth messages.

Is this deliberately left unspecified or should I use a specific setting for QoS/retain flag?

**Comment by I-Campbell** [comment]
resolved already in the devleop branch
https://github.com/eclipse/sparkplug/blame/develop/specification/src/main/asciidoc/chapters/Sparkplug_4_Topics.adoc#L179
"NBIRTH messages MUST be published with MQTT QoS equal to 0 and retain equal to false."

**Comment by pietercardoen** [comment]
Thanks!

For completeness:

NBIRTH messages MUST be published with MQTT QoS equal to 0 and retain equal to false.
