### ISSUE TITLE
Sparkplug TCK should track UTC timestamps using a configurable timestamp window

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#141]
This was discussed on the Nov 30, 2021 call. Validation of timestamps will be done in the TCK to verify that all clients are indeed using UTC timestamps. The range will be configurable but not be allowed to be more than 30 mins to ensure timestamps are not in some other timezone.

**Comment by icraggs-sparkplug** [comment]
This was done in https://github.com/eclipse/sparkplug/pull/338
