### ISSUE TITLE
Detect Sparkplug ID collisions in the TCK by tracking the MQTT client ID

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#143]
From @icraggs-sparkplug via Slack here: https://eclipse-sparkplug-wg.slack.com/archives/C01EP00EUCV/p1638290128002800

_The groupid combined with the edge node id must be unique. How could we detect if it wasn't? How could you tell that an edge node was using the same id as another edge node? From the metrics used?_

After discussion on the Nov 30, 2021 Sparkplug Spec team meeting, this will be detected by verifying that it is not the same MQTT client (by client ID) using the same group/edge id.

**Comment by icraggs-sparkplug** [comment]
The linked PR contains checks for this.

**Comment by icraggs-sparkplug** [comment]
Fixed in linked PR.
