### ISSUE TITLE
Web Console: Ensure all tests can be run from it and results reported

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#163]

**Comment by ahelmbr** [comment]
Each set of results is added to a file. But I had in mind options in the web console to specify the file location, view the complete set, and clear them if you wanted to start again. That's one thing.

**Comment by ahelmbr** [comment]
Currently each set of results is added to a file.   @icraggs-sparkplug mentioned options in the web console to 

- [ ] specify the file location, 

- [ ] view the complete set, and 

- [ ] clear them if you wanted to start again.

**Comment by ahelmbr** [comment]
Think we can now close this Issue (but I cant)
