### ISSUE TITLE
Should metric names be case sensitive

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#176]
From Ian Campbell on Slack

**Comment by wes-johnson** [comment]
This was discussed in the Sparkplug Project team meeting today (2022/1/25). The general consensus was that metric names as well as Sparkplug IDs (Group, Edge Node, and Device ID) should all be case sensitive. This could cause some issues for existing and future implementations. So, a final decision was not made but needs to be soon.

**Comment by I-Campbell** [comment]
Yes, I like case sensitive for the sparkplug protocol.
Case insensitivity, particularly for the entire UTF8, takes up some amount of space and CPU cycles, and can have some disagreements between implementations for example with accented letters.  This additional overhead is not in keeping with the philosophy behind the sparkplug protocol.

But for implementation sake, I think a sparkplug host should be allowed not to support an edge which declares two metrics named "A" and "a".  Maybe it does (best case) or maybe it doesn't.  And for maximum compatibility, an Edge SHOULD NOT publish two metrics named "A" and "a".
The case sensitivity rule would be, should an xDATA or xCMD contain metric "a", the Host and Edge MUST NOT process it as matching with the metric "A" from xBIRTH.

**Comment by matthewGEA** [comment]
The conformance requirement should be on the edge node that no two metrics, when removing sensitivity to case, would have equivalently named /overlapping/conflicting metrics.
