### ISSUE TITLE
Figure 9 - Sparkplug B Metric Structure 1 has two Metrics with the same name (OS Version)

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#179]
From Ian Campbell on Slack

**Comment by wes-johnson** [comment]
Working on getting the image source. These need to be converted to an editable format (i.e. PlantUML): https://github.com/eclipse/sparkplug/tree/develop/specification/src/main/asciidoc/assets/images/extracted-media/media

**Comment by fdesbiens** [comment]
@wes-johnson I will take this one.

**Comment by fdesbiens** [comment]
@wes-johnson We can close this one since it has been fixed by the commit above.
