### ISSUE TITLE
NCMD and DCMD messages should be allowed for metrics that were not included in an NBIRTH or DBIRTH

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#181]
There has been a lot of conversation around this on Slack - opening here for comments to track. The general consensus in todays Spec meeting (2022/01/25) is Edge Nodes should be able to handle (without crashing) metrics that were not provided in an NBIRTH or DBIRTH. This can be done in a non-normative comment that goes along with the one current stated as (in chapter 5):

* An NCMD message MUST include a metric name that was included in the associated NBIRTH message for the Edge Node.
* A DCMD message MUST include a metric name that was included in the associated DBIRTH message for the Device.

In addition to the non-normative comment - the above two MUST statements would need to change to SHOULD.

**Comment by I-Campbell** [comment]
I agree with the general consensus.

**Comment by matthewGEA** [comment]
Is the idea to allow edge nodes to have hidden commands? Or is the idea that edge nodes should be robust against publishes directed to it that it doesn't understand?

What's nice about requiring them in the NBIRTH or DBIRTH is that the commands are advertised to consumers.

**Comment by jbrzozoski** [comment]
I agree with the requirement that edge nodes must be able to handle commands to non-birthed metrics gracefully.

For the server requirement, I guess I'm okay with the wording from Wes above. There's no required implementation difference whether the spec says "MAY send NCMD to unbirthed metrics" versus "SHOULD send NCMD only to birthed metrics", but the intent is more obviously that we're trying to make robust systems and not allow hidden commands with his wording.

If the intent is really hidden commands, there are ways that don't go against Sparkplug fundamentals. For example, declare a string metric with a name like `console`, and accept "secret" commands as strings on that metric. The Ranger does uses this method to control many of the less commonly used features that didn't merit a metric of their own.
