### ISSUE TITLE
NDEATH message payload

### ISSUE THREAD

**Issue by pietercardoen** [eclipse/sparkplug#187]
Dear

I discovered a potential bug / source of confusion in the death certificate payload.

The dead certificate is generated at birth-time as it is passed as LWT to the MQTT connect message. However the metric payload is:

'''
{
        "timestamp": 1486144502122,
        "metrics": [{
                "name": "bdSeq",
                "timestamp": 1486144502122,
                "dataType": "UInt64",
                "value": 0
        }]
}
'''

A timestamp is given twice in this message while it has actually no meaning as this is the timestamp of sending the MQTT connect message. If a NDEATH message is sent from the node itself, the timestamp can have a valid timestamp but mostly, the NDEATH message is transmitted by the broker on disconnection of the edge node.

**Comment by I-Campbell** [comment]
Current wording in the develop branch is:

> An NDEATH message MAY include a timestamp.
> 
>     It should be noted that this timestamp is typically set at the time of the MQTT CONNECT message and as a result may not be useful to Host Applications. If the timestamp is set, Host Applications SHOULD NOT use it to determine corresponding NBIRTH messages. Instead, the bdSeq number used in the NBIRTH and NDEATH messages MUST be used to determine that an NDEATH matches a prior NBIRTH.

So with that, what problems do you see arising from the confusion? How do you propose they should be addressed?

**Comment by pietercardoen** [comment]
I am currently implementing a tracing tool to store historical messages for debugging of our machine. For me, it lead to confusion as I had death messages with valid timestamp and messages without valid timestamp.

I suggest to add this:
The edge node LWT may not include any timestamps as these timestamps would be set at the time of the MQTT CONNECT message. In any other case, the NDEATH message may include a timestamp

**Comment by wes-johnson** [comment]
For now NDEATH timestamps are optional and as you note are not useful if the NDEATH is delivered by the MQTT Server via the stored MQTT Will Message. This is the reason for the 'bdSeq' number. Chapter 5 (https://github.com/eclipse/sparkplug/blob/develop/specification/src/main/asciidoc/chapters/Sparkplug_5_Operational_Behavior.adoc) covers its purpose.

For now, it is just understood that the timestamp may have no meaning by consuming applications. It is important to note an Edge Node can publish its own NDEATH with a valid timestamp before sending an MQTT DISCONNECT packet too. In that case, it could have a valid timestamp.
