### ISSUE TITLE
tck build failed - Could not find org.eclipse.tahu:tahu-java:0.5.12

### ISSUE THREAD

**Issue by I-Campbell** [eclipse/sparkplug#188]
Steps to repeat:

- new install of Windows Subsystem for Linux 2 with Debian GNU/Linux 11 from [here](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions)
- sudo apt install git
- git clone https://github.com/eclipse/sparkplug.git
- cd sparkplug
- git fetch
- git switch develop
- gradlew build

==> OUTPUT:

> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':tck:compileJava'.
> \> Could not resolve all task dependencies for configuration ':tck:compileClasspath'.
>    \> Could not find org.eclipse.tahu:tahu-java:0.5.12.
>      Searched in the following locations:
>        - file:/home/username/.m2/repository/org/eclipse/tahu/tahu-java/0.5.12/tahu-java-0.5.12.pom
>        - https://repo.maven.apache.org/maven2/org/eclipse/tahu/tahu-java/0.5.12/tahu-java-0.5.12.pom
>        - https://repository.jboss.org/nexus/content/groups/public-jboss/org/eclipse/tahu/tahu-java/0.5.12/tahu-java-0.5.12.pom
>      Required by:
>          project :tck
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3m 45s

**Comment by icraggs-sparkplug** [comment]
I'm not sure it's a mistake by you - I have my own workaround.  We should make it work out of the box.

**Comment by ahelmbr** [comment]
Install the missing lib directly in your local maven works fine
