### ISSUE TITLE
TCK Instructions: need to copy more than the jar

### ISSUE THREAD

**Issue by I-Campbell** [eclipse/sparkplug#191]
https://github.com/eclipse/sparkplug/blame/develop/tck/README.md#L15

"Copy the extension file (tck/build/hivemq-extension/sparkplug-tck-3.0.0-SNAPSHOT.jar) to the HiveMQ extension directory (extensions/sparkplug-tck)."

I think it missed some files, so I copied all of the files in tck/build/hivemq-extension/ to extensions/sparkplug-tck, not just the jar.

**Comment by ahelmbr** [comment]
added some explanation in the README via #194

**Comment by icraggs-sparkplug** [comment]
Is this fixed now?

**Comment by I-Campbell** [comment]
> Is this fixed now?

Yes, thanks
