### ISSUE TITLE
TCK Webconsole : how to separate device ids

### ISSUE THREAD

**Issue by I-Campbell** [eclipse/sparkplug#192]
The UI should make it clear how to separate the list of device ids for the Edge Session Establishment Test

![grafik](https://user-images.githubusercontent.com/10012865/154609578-2136a2b3-7fb2-4214-9538-26af903712ab.png)

**Comment by ahelmbr** [comment]
Have refined this in a PR #194

**Comment by icraggs-sparkplug** [comment]
The prompt now says "The space separated list of Ids of devices connected to the edge node."

I'll close this on the assumption that this is good enough. If not please reopen with a suggestion.  Thanks.
