### ISSUE TITLE
Nested template definitons and instances

### ISSUE THREAD

**Issue by Genoil** [eclipse/sparkplug#202]
I am still struggling with Template definitions and references. Working on an implementation that uses nested Templates. Example given in pseudo code below. First, C#/Java style example, then trying to recreate those in Sparkplug. Especially the definition of Range with the nested Color Templates is something that isn't clear to me. Is this correct?

```
// OO style definitions: 

class Color {
	uint8 red,
	uint8 green,
	uint8 blue
}

class Range {
	Color from,
	Color to
}

// OO style instances:

Color MyColor = new Color(0,127,64)
Range MyRange = new Range(new Color(0,0,0), new Color(255,255,255))

// Sparkplug definitions:

Metric {
	name: Color,
	type: Template,
	value: {
		isDefinition: true,
		metrics:[
			Metric {
				name: red,
				type: UInt8
			},
			Metric {
				name: green,
				type: UInt8
			},
			Metric {
				name: blue,
				type: UInt8
			},
		]
	}
}

Metric {
	name: Range,
	type:Template,
	value: {
		isDefinition: true,
		metrics:[
			Metric {
				name: from,
				type: Template,
				value: {
					isDefinition: false,
					templateRef: Color
				}
			},
			Metric {
				name: from,
				type: Template,
				value: {
					isDefinition: false,
					templateRef: Color
				}
			}
		]
	}
}

// Sparkplug instances:

Metric {
	name: MyColor,
	type: Template,
	value: {
		isDefinition: false,
		templateRef: Color,
		metrics:[
			Metric {
				name: red,
				type: UInt8,
				value: 0
			},
			Metric {
				name: green,
				type: UInt8,
				value: 127,
			},
			Metric {
				name: blue,
				type: UInt8,
				value: 64
			},
		]
	}
}

Metric {
	name: MyRange,
	type:Template,
	value: {
		templateRef:Range
		metrics:[
			Metric {
				name: from,
				type: Template,
				value: {
					isDefinition: false,
					templateRef: Color
					metrics:[
						Metric {
							name: red,
							type: UInt8,
							value: 0
						},
						Metric {
							name: green,
							type: UInt8,
							value: 0,
						},
						Metric {
							name: blue,
							type: UInt8,
							value: 0
						},
					]
				}
			},
			Metric {
				name: from,
				type: Template,
				value: {
					isDefinition: false,
					templateRef: Color,
					metrics:[
						Metric {
							name: red,
							type: UInt8,
							value: 255
						},
						Metric {
							name: green,
							type: UInt8,
							value: 255,
						},
						Metric {
							name: blue,
							type: UInt8,
							value: 255
						}
					]
				}
			}
		]
	}
}
```

Also, it isn't fully clear to me if sending a Template definition before sending any instances is mandatory? Haven't seen any complaining clients yet. And finally, am I allowed to add values to Template definitions, just like initial values of OO objects?

**Comment by wes-johnson** [comment]
So - there is a lot to cover here and I haven't gotten to expanding on this portion of the spec yet. As a starting point, I'd suggest this: https://github.com/eclipse/tahu/blob/develop/java/examples/udt/src/main/java/org/eclipse/tahu/SparkplugExample.java

Template definitions do need to be sent in the NBIRTH message. I don't think in the next iteration of the spec they will be required to be in the NBIRTH. However, Host Applications such as MQTT Engine do need to know about them. So, if they haven't been sent previously, they need to be in the NBIRTH.

Template definitions can include default values.

You may find this doc helpful in seeing how Templates (UDTs in Ignition) work in Cirrus Link's Sparkplug modules: https://docs.chariot.io/display/CLD80/User+Defined+Types+%28UDTs%29+within+Transmission

You could even run through this doc above and use this: https://github.com/eclipse/tahu/blob/develop/java/examples/listener/src/main/java/org/eclipse/tahu/SparkplugListener.java to 'listen' to messages as they flow through the MQTT Server. It should give you a good idea of valid structures.
