### ISSUE TITLE
Define basic test flows for both profiles (edge and host)

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#21]
There should be three profiles at this point:
edge
host
primary host

**Comment by icraggs-sparkplug** [comment]
Attaching a first pass doc with questions. 
[Sparkplug profiles.txt](https://github.com/eclipse/sparkplug/files/6172508/Sparkplug.profiles.txt)

**Comment by icraggs-sparkplug** [comment]
This is done.
