### ISSUE TITLE
Out of order NBIRTH / NDATA messages

### ISSUE THREAD

**Issue by dcrowe** [eclipse/sparkplug#212]
Hi.

I have run into a race-condition where a Sparkplug client sends an NBIRTH immediately followed by NDATA and while the broker receives the messages in order, the downstream consumer receives that messages out-of-order.

It looks to me like the MQTT spec doesn't require the broker to maintain order between topics:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718105

In my case, this is a particular problem because we are using aliases to exclude metric names and we are unable to successfully decode the initial NDATA message. I can identify occurrences my eye, but am unsure how to identify it programmatically.

Is there a recommended or official process to resolve this issue?

**Comment by I-Campbell** [comment]
Please see closed issue #93 which addresses this. by adding this chapter:
https://github.com/eclipse/sparkplug/blob/develop/specification/src/main/asciidoc/chapters/Sparkplug_5_Operational_Behavior.adoc#sparkplug-host-application-message-ordering

Only out of curiosity, which MQTT server and which MQTT client do you use where this out of order issue occurs?  Did you confirm with wireshark, that the out of order messages were seen on the wire (i.e. it was not a feature of the subscribing client)?

**Comment by dcrowe** [comment]
The broker is [EMQX](https://www.emqx.io/) running a cluster of three nodes.
The receiving client is Paho for Java.

I haven't confirmed it with wireshark, but I can put together a minimal repro

**Comment by dcrowe** [comment]
Thanks for the pointer to the doc. That should help.
