### ISSUE TITLE
Rebirth, bdSeq and last will?

### ISSUE THREAD

**Issue by Llorx** [eclipse/sparkplug#216]
As the spec says, when you connect, you must set the last will to a `NDEATH` command with a `bdSeq` that will match the `NBIRTH` command that you are going to send.

Now, if a node receives the Rebirth command, it should send again the `NBIRTH` command with the `bdSeq` increased. This will render the last will invalid as it has the previous `bdSeq` number.

To update it, you must reconnect, which is simply a Reboot?

**Comment by icraggs-sparkplug** [comment]
I thnk this is the same point as https://github.com/eclipse/sparkplug/issues/199.
