### ISSUE TITLE
Figure 1 on pages 6 and 14 may need some modifications

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#223]
Raised by Bryce:

Implication of "Figure 1" Pages 6 and 14
I ask if the figure could be edited in the following ways.

    The "SCADA/IIoT Host (Sparkplug) should be labelled as the Primary Application.
    The Arrows to the MES, Historian, and Analytics should only have an arrow point to these boxes and not to the MQTT Server. This implies other non-edge node clients are able to transmit Sparkplug messages.
    The arrowheads are made more visible.
    If a hot standby is shown, it should be labelled as such and may have a bidirectional arrow with the MQTT Server.

**Comment by fdesbiens** [comment]
@wes-johnson I am working on this issue right now.
