### ISSUE TITLE
Dataset questions

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse/sparkplug#226]
1. One assertion says:

_This values in the types array MUST be one of the enumerated values as shown in the [Sparkplug Basic Data Types]_

In the protobuf definition file, the list of basic data types is:

    // Basic Types
    Int8            = 1;
    Int16           = 2;
    Int32           = 3;
    Int64           = 4;
    UInt8           = 5;
    UInt16          = 6;
    UInt32          = 7;
    UInt64          = 8;
    Float           = 9;
    Double          = 10;
    Boolean         = 11;
    String          = 12;
    DateTime        = 13;
    Text            = 14;

but another assertion says:

_The value supplied MUST be one of the following types: uint32, uint64, float, double, bool, or string._

I think the latter one is correct, although the protobuf definition also contains:

    DataSetValueExtension extension_value   = 7;

which I don't think gets mentioned anywhere, except in the comments in the protobuf file.

2, One assertion about the types array says:

_This MUST be included in DataSet Definitions in NBIRTH and DBIRTH messages._

But the types array is not optional in the DataSet definition (should it be?). This implies that the types array could be optional in NDATA/DDATA messages - is that intended?

3. The assertion for num_of_columns says:

_This MUST be an unsigned 64-bit integer representing the number of columns in this DataSet._

but in the protobuf file, num_of_columns is optional. This seems contradictory?

**Comment by I-Campbell** [comment]
> The value supplied MUST be one of the following types: uint32, uint64, float, double, bool, or string.

These are protobuf data types 

> This values in the types array MUST be one of the enumerated values as shown in the [Sparkplug Basic Data Types]

These are Sparkplug datatypes

Interesting point about the extensions. I would almost suggest deleting the extensions.  But if they are in the protobuf description, then the spec wording must agree.

**Comment by icraggs-sparkplug** [comment]
The basic types list is longer than the list actually allowed in the types array so I think the assertion:

_This values in the types array MUST be one of the enumerated values as shown in the [Sparkplug Basic Data Types]_

is wrong.  (And the internal header link isn't right)

**Comment by I-Campbell** [comment]
If we look at the [old specification](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf) , it shows how each DataSet.types is mapped to a protobof type. 
On page 55, it shows the datasetvalue datatypes.
So If DataSet.types is 1,2,3,5,6 or 7 , the value is stored in a protobuf uint32 (DataSet.Row.DataSetValue.int_value)
If DataSet.types is 4 or 8, then the value is stored in a protobuf uint65 (DataSet.Row.DataSetValue.long_value)

Protobufs does not have as many datatypes as sparkplug.

It is in keeping with the storage of metric values (Metric.datatype vs Metric.value)

You are right that the link "Sparkplug Basic Data Types" isn't working.
