### ISSUE TITLE
Sparkplug™ 

### ISSUE THREAD

**Issue by kevinherron** [eclipse/sparkplug#24]
It looks like someone went overboard with a find and replace and "Sparkplug™" is everywhere in the spec, including protobuf definitions and topic names, among other places it's not likely intended:

```
syntax = "proto2";

package org.eclipse.tahu.protobuf;

option java_package         = "org.eclipse.tahu.protobuf";

option java_outer_classname = "Sparkplug™BProto";

message Payload {

...truncated...
```

**Comment by icraggs-sparkplug** [comment]
This seems to have been fixed - at least in the code mentioned.  But it's inconsistent - section 10 doesn't have the TM on Sparkplug whereas the rest do most of the time.  

Is the TM needed so much?  The [Eclipse Trademark usage guidelines](https://www.eclipse.org/legal/logo_guidelines.php) say:

_The appropriate trademark symbol (i.e. ™ or ®) must appear at both the first and most prominent use of Eclipse trademarks, and with all occurrences of the Eclipse logo. When you use an Eclipse Trademark you must include a statement attributing the trademark to the Eclipse Foundation, Inc. For example, "'Eclipse', 'Built on Eclipse' and 'Eclipse Ready', 'BIRT', 'Orion' are trademarks of Eclipse Foundation, Inc."_

I think the Sparkplug name needs to be prefixed with Eclipse more often:

_All Eclipse projects must be identified as being Eclipse projects. Therefore, when referencing an Eclipse project, we ask that both the first and the most prominent reference to the project on each page is identified as Eclipse [project name] (e.g., Eclipse Graphical Modeling Framework (GMF) or in the case of a project name that already includes Eclipse, Eclipse Communication Framework (ECF)). Subsequent references may drop the Eclipse identifier._

**Comment by wes-johnson** [comment]
I believe this has now all been addressed including @icraggs comments on the use of 'Eclipse' before Eclipse based projects.
