### ISSUE TITLE
MUST DBIRTH messages include current values for all metrics?

### ISSUE THREAD

**Issue by ginger-OS** [eclipse/sparkplug#250]
Trying to pass TCK test suite with our client implementation. 

Test FAILS on "DBIRTH messages MUST include current values for all metrics". 

Spec however states (15.1.5) that Metric does not need to include value when is_null is set. 

Which statement is correct?

**Comment by ginger-OS** [comment]
Well I haven’t fully checked whether or not that is the case, but the TCK code only calls Utils.hasValue(metric), not metric.hasIsNull(). Now I added the latter, but that for some reason returns false regardless the presence of is_null.

**Comment by icraggs-sparkplug** [comment]
The spec doesn't mention is_null at all in section 5, and the conformance statement in section 5 only states that 

     DBIRTH messages MUST include current values for all metrics.

so I didn't notice the is_null flag which is only mentioned in section 6, and not in any conformance statement. The conformance statement could be changed to:

      Every metric in DBIRTH messages must include a current value or have the is_null flag set to true.

Or something similar.

**Comment by ginger-OS** [comment]
Thanks. I made a change in the test code so that it also checks for is_null. For some reason all my metrics return false on Metric::hasIsNull(), but that is possibly a fault in my client implementation.

**Comment by icraggs-sparkplug** [comment]
@wes-johnson would you like to update the spec for this?
