### ISSUE TITLE
Template definitions and instances

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse/sparkplug#292]
Section 6.4.14

_A Template Instance MUST include all members that were included in the corresponding Template Definition in a NBIRTH or DBIRTH message._

_A Template Instance MAY include only a subset of the members that were included in the corresponding template definition in a NDATA or DDATA message._

I'm trying to work out what the second sentence means as it seems to conflict with the first, unless the second refers to template instances in a DATA message and the first only applies to BIRTH messages.  It this is what the sentences mean, I think they would be clearer like this:

_A Template Instance in a NBIRTH or DBIRTH message MUST include all members that were included in the corresponding Template Definition._

_A Template Instance  in a NDATA or DDATA message MAY include only a subset of the members that were included in the corresponding template definition._

And definitions are only allowed in BIRTH messages?

**Comment by Llorx** [comment]
Asking a question about this here: https://github.com/eclipse-sparkplug/sparkplug/issues/431

The main concern is if in a template instance in a DBIRTH command I have to send the full detailed metric definition, exactly the same as the corresponding Template Definition, or I just need to send the same metrics but compressed to the minimum info like a DDATA. I mean, not sending the name and just the alias, por example.
