### ISSUE TITLE
Additional images need to be converted from png files to plantuml

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#295]
These images still need to be converted:

* specification/src/main/asciidoc//assets/images/extracted-media/media/image11.png
* specification/src/main/asciidoc//assets/images/extracted-media/media/image12.png
* specification/src/main/asciidoc//assets/images/extracted-media/media/image13.png
* specification/src/main/asciidoc//assets/images/extracted-media/media/image14.png
* specification/src/main/asciidoc//assets/images/extracted-media/media/image15.png
* specification/src/main/asciidoc//assets/images/extracted-media/media/image16.png

**Comment by fdesbiens** [comment]
@wes-johnson I will take care of this. Please assign to me.
