### ISSUE TITLE
Approaches to testing remaining assertions

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse/sparkplug#322]
We're up to 93% coverage, and I will go back to review all the tests but I wanted to complete the set first. I have some questions on the outstanding ones:

- There are two assertions related to timestamps in UTC, which are marked as untestable. I have a test for one of them, which I think will work (checking the timestamp value within a configurable window). If we agree this approach can work, then we can mark these assertions as testable.
- Section 5.10 Multiple Server Topologies. (4 assertions). The first three directly need more than one MQTT server to test, which I don't think we're going to do at least in this version of the TCK. So I suggest those three are marked as untestable: 
  - operational-behavior-primary-application-state-with-multiple-servers-state, 
  - operational-behavior-primary-application-state-with-multiple-servers-single-server,
  - operational-behavior-primary-application-state-with-multiple-servers-walk. 
Unless there is a suggestion how to test?
- Section 5.9. Message Ordering. I can build a separate test to force this scenario. Assertion operational-behavior-host-reordering-success contains no SHOULD statements (but some "can"s) - should it be reworded?
- The following assertions require checking the reaction of the Host Application 
  - operational-behavior-edge-node-termination-host-action-ddeath-devices-tags-stale
  - operational-behavior-edge-node-termination-host-action-ddeath-devices-offline
  - operational-behavior-edge-node-termination-host-action-ndeath-node-offline
  - operational-behavior-edge-node-termination-host-action-ndeath-node-tags-stale
  - operational-behavior-edge-node-termination-host-action-ndeath-devices-offline
  - operational-behavior-edge-node-termination-host-action-ndeath-devices-tags-stale
  Are we happy to request a manual check by the tester here, with a confirmation dialog (passed/failed)?

FYI @ahelmbr

**Comment by ahelmbr** [comment]
My opinion to the questions:
1. Agree to proposal: checking the timestamp value within a configurable window. 
2. Could also be solved with different ports?
3. Should be reworded IMHO
4. Yes - manual check is enough

**Comment by icraggs-sparkplug** [comment]
1. Shall I create a PR to change these assertions, or do you want to do it Wes?

2. Different ports might enable some of the assertions to be tested, but not all I think. I'll try it out.

**Comment by wes-johnson** [comment]
@icraggs-sparkplug - I'm all for you creating a PR for these :)

**Comment by icraggs-sparkplug** [comment]
All now done.
