### ISSUE TITLE
Some Spec inter document 'References' seems not to reference correct sections.

### ISSUE THREAD

**Issue by larspaulsen** [eclipse/sparkplug#331]
Some inter document 'References' seems not to reference actual document sections, such as in attached example. If one search for '3.1.4' en the entire document then no such reference exist and section '3.1. MQTT Server(s)' do not contain any sub sections.

Other similar references exist.

![SparkPlug Spec Reference Error](https://user-images.githubusercontent.com/13814018/194426141-b262d566-d27e-4b3a-b0e6-8a87930e4d68.png)

**Comment by wes-johnson** [comment]
This issue was created against the old v2.2 release of the spec. This no longer applies to the current working v3.0.0-SNAPSHOT specification. All stale section pointer changes have already been made.
