### ISSUE TITLE
TCK Source file headers need correcting

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse/sparkplug#339]
Many TCK source files which I did not create do not have the correct copyright and license header.

**Comment by wes-johnson** [comment]
Fixed here: https://github.com/eclipse/sparkplug/commit/1d6e88034dbbff0eab912b2a6abd451e5f13313f

**Comment by icraggs-sparkplug** [comment]
I was thinking of the web console source files.

**Comment by icraggs-sparkplug** [comment]
Now done.
