### ISSUE TITLE
TCK Multiple MQTT Server Topologies assertions to finish

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#349]
Section 5.10 - Multiple MQTT Server Topologies - 5 assertions to be implemented. It is suggested that maybe an MQTT server with multiple ports could simulate it. I think it's possible, but not for all 5.

**Comment by icraggs-sparkplug** [comment]
There are placeholder multple broker tests for this:

https://github.com/eclipse/sparkplug/blob/develop/tck/src/main/java/org/eclipse/sparkplug/tck/test/host/MultipleBrokerTest.java

https://github.com/eclipse/sparkplug/blob/develop/tck/src/main/java/org/eclipse/sparkplug/tck/test/edge/MultipleBrokerTest.java

**Comment by icraggs-sparkplug** [comment]
Done in https://github.com/eclipse/sparkplug/pull/370 and https://github.com/eclipse/sparkplug/pull/369
