### ISSUE TITLE
TCK Host Application Message Ordering assertions to finish

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#350]
Section 5.9 - Host Application Message Ordering - 4 assertions to implement

**Comment by icraggs-sparkplug** [comment]
There's a placeholder host MessageOrderingTest for this 

https://github.com/eclipse/sparkplug/blob/develop/tck/src/main/java/org/eclipse/sparkplug/tck/test/host/MessageOrderingTest.java

**Comment by icraggs-sparkplug** [comment]
Addressed by PR https://github.com/eclipse/sparkplug/pull/366

**Comment by icraggs-sparkplug** [comment]
Done.
