### ISSUE TITLE
clarify timing requirements or available alternatives of NDATA / DDATA

### ISSUE THREAD

**Issue by I-Campbell** [eclipse/sparkplug#42]
7.2 NDATA Section mentions: "RBE or time based metric EoN"
7.4 DDATA Section mentions only Report by Exception.

Clarify whether both RBE or time based reporting are allowed.

Reword the specification to reflect this.

**Comment by I-Campbell** [comment]
My thoughts: 
1. NDATA and DDATA should allow the same reporting methods
2. Both reporting options would be nicer.

**Comment by wes-johnson** [comment]
Fixed by PR #88
