### ISSUE TITLE
Complete section 'Introduction - Editing Convention' of the Sparkplug Spec

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#45]
Additional work related to #31

**Comment by icraggs-sparkplug** [comment]
Is this section intended to be similar to the Conventions section of, for instance, the Jakarta annotations specification https://jakarta.ee/specifications/annotations/2.0/annotations-spec-2.0.html#conventions ?  

The contents of which are:

    2.4. Conventions
    The keywords ‘MUST’, ‘MUST NOT’, ‘REQUIRED’, ‘SHALL’, ‘SHALL NOT’, ‘SHOULD’, ‘SHOULD NOT’, ‘RECOMMENDED’, 
    ‘MAY’ AND ‘OPTIONAL’ in this document are to be interpreted as described in RFC 2119.

    Java code is formatted as shown below:

    package com.wombat.hello;

    public class Hello {
        public static void main(String[] args) {
            System.out.println("Hello world");
        }
    }

**Comment by wes-johnson** [comment]
Yes - that is the general idea.

**Comment by wes-johnson** [comment]
Actually - In reviewing I may have meant something more like this:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718017

Basically the idea is to highlight all normative statements in the spec and denote that in the intro section. On that note, I found these links for asciidoc:
https://blog.mrhaki.com/2018/09/awesome-asciidoctor-document-attributes.html
https://github.com/eclipse-ee4j/beanvalidation-spec/blob/master/docinfo/index-docinfo.html

A quick try didn't work for. So, I think two issues need to be addressed here. One is 'highlighting' as done in the MQTT spec. The other is what @icraggs brought up in his comment on Feb 8. I thought those were also already in place but can't seem to find them at the moment.
