### ISSUE TITLE
MQTT version 5.0

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse/sparkplug#65]
I think we need to define how Sparkplug relates to MQTT 5.0, not just 3.1.1.  The 5.0 standard has been published for almost two years now and will see increasing adoption. 

I don't think there need be any substantive changes to be able to use MQTT 5.0, as it is a superset of 3.1.1, so all it will amount to is saying that Sparkplug will work with both, and that when MQTT is referred to, it can mean either version.

It's possible that if any specific MQTT functionality is mentioned the terminology may differ between 5.0 and 3.1.1 but so far I've not noticed any.  Retained messages, for instance, remain the same. 

The "clean session" flag is one difference in MQTT 5.0 - it becomes the clean start flag combined with the session expiry interval.  But I don't think "clean session" is mentioned anyway.

The biggest impact _might_ be on the TCK, if we need to ensure it works on both versions.

**Comment by wes-johnson** [comment]
There have been recent additions to the spec with regard to clean session. Since we are targeting MQTT v5 support at this point as well, the spec needs to be updated to reflect the clean start flag when/if MQTT 5 is being used.

**Comment by srwarner** [comment]
Likely we also need to state that SessionExpiry should be 0 (given that there's no Session to restore to given the CleanStart=0 requirement)
