### ISSUE TITLE
Sanity check Sparkplug clients against an MQTT v5.0 Server

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#75]
Before making all of the changes to the specification around support for MQTT v5.0 we should make sure there are no issues with it. Inductive Automations's Ignition platform, with Hive MQ's v5.0 compliant MQTT Server, and Cirrus Link's MQTT Engine and Transmission modules should make for a good sanity check.

**Comment by icraggs-sparkplug** [comment]
So as a starting point, I ran the Tahu C client test program in MQTT 5.0 mode against an MQTT 5.0 server.  It behaved the same as when using MQTT 3.1.1.

With the combination of software above, what sort of test scenario did you have in mind?

**Comment by wes-johnson** [comment]
My understanding is the QoS1, retained, and Will behavior didn't change as it pertains to Sparkplug. But, I think verifying the primary host ID and Will messages work as they do with MQTT 3.1.1 would be worthwhile. This is the only thing I can think of the might be different. But again, I think it should just work.

**Comment by wes-johnson** [comment]
Closing as this will be fully validated in the end by a v5 compliant MQTT Server
