### ISSUE TITLE
[Bug/Typo] Section 8.3 MQTT Device Session Establishment

### ISSUE THREAD

**Issue by shantanoo-desai** [eclipse/sparkplug#90]
For the following [Section 8.3 MQTT Device Session Establishment](https://github.com/eclipse/sparkplug/blob/master/specification/Sparkplug.adoc#mqtt-device-session-establishment)

There is either an incomplete sentence for Bullet Point 4 or a typo.

> State #4 in the session diagram represents the state at which the device is ready to report all of its metric information to the MQTT EoN node as defined in Sparkplug™. It is the responsibility of the EoN node (logical or physical) to put this information in a form defined in 0,

And an empty Bullet Point 5.

Is this a typo that needs to be addressed and what does the Bullet Point 4 stated above mean in this context (`information in a form defined in 0,`)?

**Comment by I-Campbell** [comment]
In https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf
"Zero, comma, line break, five, full stop" links to section 7.3.1. Device Birth Certificate (DBIRTH)
So I think "a form defined in 0,
5." should be changed to "a form defined in 7.3.1. Device Birth Certificate (DBIRTH)".  Or the new chapter number for that section.

Develop branch still shows the blank Bullet Point 5 https://github.com/eclipse/sparkplug/blame/develop/specification/src/main/asciidoc/chapters/Sparkplug_5_Operational_Behavior.adoc#L204

**Comment by shantanoo-desai** [comment]
@I-Campbell should I go ahead and update it or it this something only a committee member is allowed to do?

**Comment by wes-johnson** [comment]
This was already fixed in a previous commit - there is now a asciidoc link to the DBIRTH section (https://github.com/eclipse/sparkplug/blob/develop/specification/src/main/asciidoc/chapters/Sparkplug_5_Operational_Behavior.adoc). However, the blank bullet is still there. I have that cleaned up in my fork and will include it in my next PR.
