### ISSUE TITLE
Consolidate MQTT requirements in a single place in 'Operational Behavior'

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#92]
* Disallow clean_session=false connections due to potential problems
* Explicitly state QoS requirements for all messages
* Explicitly state retain flag requirements for all messages

**Comment by andy1547** [comment]
@wes-johnson I've read over the v2.2 and development spec and have a few questions about state management. 

1. When a Node is disconnecting intentionally (non-persistent connection), should DDeaths be published if its connected Devices are still online during the shutdown? In the Node's perspective the Devices are still be connected after the connection closes.
2. When a Node is disconnecting intentionally (non-persistent connection), should a NDeath be explicitly published before sending an MQTT Disconnect packet? Or should NDeaths never be explicitly published by the Node and only be delivered as part of the last will and testament (on ungraceful disconnects)?
3. If several of the Node's Devices have published DBirths and then a ungraceful disconnection occurs, after the Node comes back online does it need to publish DBirths again (as from the Node's perspective the Devices have remained connected)? I'm unable to infer the context from "if this is the first time this device has been seen".
4. When the Primary application receives a NDeath packet, should it set the Device metrics to stale? On the event of a ungraceful disconnect where a NDeath is received through the last will and testament, the Device may have technically still been connected to the Node despite the loss of comms between the node and MQTT server.

**Comment by wes-johnson** [comment]
These have already been added
