### ISSUE TITLE
[Bug] Numerical Section Numbers in Payload Definition v1.0 Document are not generated accordingly to the Table of Content

### ISSUE THREAD

**Issue by shantanoo-desai** [eclipse/sparkplug#99]
Official PDF Document continues the Section numbers from the main description document e.g. 

```
13. Introduction
14. Sparkplyg B MQTT Payload Definition
15. Sparkplug Bv1.0 Payload Components
16. ....
```

However in the asciidoc of certain sections the section number when citing within the same document is set from 1 onwards.

## Example

__15. Sparkplug Bv1.0 Payload Components__

In the Subsection `15.1.1 Payload` the `payload` description mentions `metrics` as a key which has the following statement

> this is an array of metrics representing key/value/datatype values. Metrics are further defined in _section 3.1.2_

When you follow the ToC of the complete documentation, this might point to a wrong part all together.

Whereas the asciidoc link should point to Section __15.1.2 Metric__ which is subsequently mentioned.

**Comment by wes-johnson** [comment]
The new working spec (3.0.0-SNAPSHOT) has an automated mechanism for dealing with issues like this. See the current example here: https://drive.google.com/file/d/1DkARtVzbc4xbUIQ7wxbk6NFIm1HkJXoO/view
